[DML] Update WebNN DML backend ops support status for Chromium fork
webmachinelearning/webmachinelearning.github.io pull request #53
Opened 2023-08-10 06:12 UTC by ibelem

Based on @fdwr's comments:

> The Chromium fork supports all except {LSTM/cell, GRU/cell, HardSwish}. 

@anssiko PTAL

![10 239 115 52_4000_webnn-status_](https://github.com/webmachinelearning/webmachinelearning.github.io/assets/5017359/9af7906f-b650-4af1-9d45-09e88f5f212c)

2023-08-10 12:30 UTC, anssiko requested changes
@ibelem, could we add a footnote with a link to the "Chromium fork" so interested folks can peek in? IIRC this fork is public. This might facilitate further contributions to the implementation.

2023-08-10 15:22 UTC, anssiko commented
On a second thought, we probably want to leave the link to the Chromium fork out for now given the plan is to upstream the code soonish.

While I'm here, on our WG call today, we agreed we want to remove "v2" occurrences from web developer facing documentation, since v1/v2 labeling is not helpful to web developers. Thus could you remove "v1" from the following in this or subsequent PR:

>The total number of WebNN v1 ops is 60

2023-08-10 23:34 UTC, ibelem commented
Thanks @anssiko for the feedback from WG call, removed "v1" relevant in the squashed PR. PTAL

2023-08-11 05:00 UTC, anssiko approved these changes
Thanks!

2023-08-11 05:01 UTC, merged