Update implementation status (TFLite + Core ML)
webmachinelearning/webmachinelearning.github.io pull request #78
Opened 2024-06-05 08:10 UTC by ibelem

- The XNNPack backend was replaced by TFLite, merge the original MLService data into TFLite column
- Add Core ML column 
- Update ONNX Runtime Web support versions from "main" to "1.18.0"

![10 239 115 52_4000_webnn-status_](https://github.com/webmachinelearning/webmachinelearning.github.io/assets/5017359/62b163a9-1e93-49de-9ac6-2bb4b79cae7d)

@anssiko PTAL

2024-06-05 14:02 UTC, anssiko requested changes
Thanks for this contribution! I have one comment regarding one image asset.

2024-06-05 14:02 UTC, anssiko commented on assets/images/implstatus/mac.svg
It would be more appropriate to use the [macOS wordmark from Wikipedia](https://commons.wikimedia.org/wiki/File:MacOS_logo.svg) that is in public domain. Please also note in the commit message the source.

2024-06-06 00:16 UTC, ibelem commented on assets/images/implstatus/mac.svg
I never successfully to use any svg logos from Wikipedia in company network. 

```
Access Failure
[commons.wikimedia.org/wiki/File:MacOS_logo.svg](https://commons.wikimedia.org/wiki/File:MacOS_logo.svg)
```
These svg logs come from wpt.fyi, e.g.

```
https://wpt.fyi/static/mac.svg
https://wpt.fyi/static/linux.svg
https://wpt.fyi/static/win.svg
```
The new commit uses the https://wpt.fyi/static/ back for them. PTAL.

2024-06-06 00:18 UTC, ibelem commented
@anssiko PTAL the new commit update, thanks!

2024-06-06 12:23 UTC, anssiko approved these changes

2024-06-06 12:23 UTC, merged